os:
  - linux
  - osx
language: ruby
rvm:
  - 2.2.2
env:
  - BERKSHELF_PATH=/tmp/
before_install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash
  - gem install bundler
install:
  - bundle install --without integration
  - bundle exec berks vendor /tmp/cookbooks
  - cp test/support/dummy-validation.pem /tmp/validation.pem
  - cp test/support/client.rb /tmp/client.rb
  - cp test/support/dna.json /tmp/dna.json
script:
  - rvm reset # To use the embedded ruby in chef-client
  - sudo chef-client -z -c /tmp/client.rb -j /tmp/dna.json # Run chef in zero mode
  - '[ -f ~/.bash_profile ] && source ~/.bash_profile || source ~/.profile && source /etc/profile' # Apply new env vars
  - rvm use ruby-2.2.2 # To use the rvm ruby and custom gems
  - bundle exec rake # Test all
